version: "3.8"
services:
    app:
        container_name: obfuscation-service
        build:
            context: .
        environment:
            - LOG_ROTATION_FILENAME=
        env_file: .env
        ports:
            - 127.0.0.1:${SERVICE_PORT:-8204}:${SERVICE_PORT:-8204}
